### ISSUE TITLE
Get the methods

### ISSUE THREAD

**Issue by alesanabriav7** [emanueleDiVizio/ChromeCast-ReactNative-V3#1]
Hi @emanueleDiVizio thank you for do this, a question I need use this lib for a custom chromecast integration but I only need the methods on react native and I see the lib export a component there are someway you can make this lib like this https://github.com/charliesbox/react-native-google-cast that expose the methods and the view implementation is up to the developer. thank you.

**Comment by emanueleDiVizio** [comment]
Hi @developersoul, thanks for reaching out! 

Actually, those methods are not exported because Google Cast SDK V3 doesn't allow it anymore, as the native components are responsible to manage device discovery and connection. 
There are still some methods exposed to provide Video playback controls. 
Feel free to check [test app](https://github.com/emanueleDiVizio/ChromeCast-ReactNative-V3---Test-App) for reference.
